name: 'Glitch Project Sync'
author: 'Kanad Gupta'
branding:
  color: blue
  icon: refresh-cw
description: 'Sync the contents of your GitHub repository with your project on Glitch'
inputs:
  project-id:
    description: 'ID of your Glitch Project'
    required: true
  auth-token:
    description: 'Auth token for your Glitch Project'
    required: true
  path:
    description: 'Optional relative path to a specific folder to import'
    required: false
outputs:
  response: # id of output
    description: 'Response from Glitch API'
runs:
  using: 'node12'
  main: 'dist/index.js'
