name: 'Glitch Project Sync'
author: 'Kanad Gupta'
branding:
  color: blue
  icon: refresh-cw
description: 'Sync the contents of your GitHub repository with your project on Glitch'
inputs:
  auth-token:
    description: 'Auth token for your Glitch Project'
    required: true
  project-id:
    description: 'ID of your Glitch Project'
    required: true
  path:
    description: 'Optional relative path to a specific folder to import'
    required: false
  repo:
    description: 'Optional GitHub repo if not using current repo (e.g., `octocat/Hello-World`)'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
