name: Glitch Sync (Demo)

# Triggered when code is pushed to any branch in a repository
on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Glitch Project (demo)
      uses: dist/index.js
      with:
        project-id: '${{ secrets.SANDBOX_PROJECTID }}'
        auth-token: '${{ secrets.SANDBOX_AUTHTOKEN }}'
        path: 'demo' # sync demo folder
